### ISSUE TITLE
Nova Scotia, Canada 4/ 24&25&27 /2020 data errors

### ISSUE THREAD

**Issue by syl1010** [CSSEGISandData/COVID-19#2377] opened 2020-04-25 11:29 UTC
The data for Nova Scotia is listed as 

Nova Scotia,Canada,44.681999999999995,-63.7443,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,7,12,14,15,21,28,41,51,68,73,90,110,122,127,147,173,193,207,236,262,293,310,310,342,407,428,445,474,517,549,579,606,649,675,721,737,772,827,-1,-1,-1

Note: that the last reported values were 850, 865, 873 not -1,-1,-1

please fix

**Comment by econ-erik** [comment] 2020-04-25 11:49
I believe @syl1010 meant that the error corresponds to the data for Nova Scotia for 4/24/2020. 

The data is also incorrect for the Grand Princess it's been switched to -1 (starting 4/22/2020) while in the Government of Canada / Canada Public Health Infobase data, it's still is being listed as 13 (Repatriated Travellers).

**Comment by syl1010** [comment] 2020-04-25 12:07
econ-erik  
Correct - 4/24/2020 - thanks

**Comment by Lucas-Czarnecki** [comment] 2020-04-25 18:17
Seconded. Time-series reports -1 for Deaths and Confirmed cases. 

Nova Scotia is also missing entirely from the 04-24-2020 daily report.

**Comment by econ-erik** [comment] 2020-04-26 03:06
Nova Scotia and the Grand Princess are still showing up as -1 in the data for 4/25. The GoC website has them at 865 and 13 respectively for 4/25 (11:06 EDT).

**Comment by econ-erik** [comment] 2020-04-27 15:20
Just an FYI, it looks like the error has been picked up with web data portion of the project (likely where it originated) so hopefully that will lead to corrected daily reports in the future. Commit here: https://github.com/CSSEGISandData/COVID-19/commit/430e124f81f8b4f306dae1b8d50a5179b3d0ced5

**Comment by Lucas-Czarnecki** [comment] 2020-04-27 17:53
Just saw JHU update their time-series data to fix Nova Scotia and Diamond Princess b29f336fdced9e4b29a257c44632e0e804ba8c87

Daily reports, however, are still adversely affected. Hoping they update those too.

**Comment by CSSEGISandData** [comment] 2020-05-02 01:29
Hello! This issue has been fixed in the time series tables. Thanks!

**Closed by CSSEGISandData** 2020-05-02 01:29 UTC

**Comment by alfkoehn** [comment] 2020-05-04 10:55
> The data for Nova Scotia is listed as
> 
> Nova Scotia,Canada,44.681999999999995,-63.7443,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,7,12,14,15,21,28,41,51,68,73,90,110,122,127,147,173,193,207,236,262,293,310,310,342,407,428,445,474,517,549,579,606,649,675,721,737,772,827,-1,-1,-1
> 
> Note: that the last reported values were 850, 865, 873 not -1,-1,-1
> 
> please fix

I just saw that this has been fixed, so this issue can probably be closed.
