### ISSUE TITLE
Washington data - new case / death counts unavailable

### ISSUE THREAD

**Issue by rainiernate** [CSSEGISandData/COVID-19#1885] opened 2020-04-02 00:54 UTC
Not sure if this is being addressed some other way but the Washington State Department of Health has not updated their confirmed cases or death counts in 4 full days citing technical difficulties. This site aggregates all of the various state counties cases into one page which is where several scrapers have pulled statewide data from. Until now there doesn't seem to be a good source of up to date case count for WA state unless there's another official source.

WA DOH site - see statement on their site: https://www.doh.wa.gov/emergencies/coronavirus

**Comment by amalic** [comment] 2020-04-02 01:06
It's missing for all of US

Duplicate of this issue: https://github.com/CSSEGISandData/COVID-19/issues/1882

**Comment by oltdaniel** [comment] 2020-04-02 01:08
@rainiernate Please close due to duplicate.

**Closed** 2020-04-02 01:13 UTC
