### ISSUE TITLE
San Francisco County, US has not updated for 7 days.

### ISSUE THREAD

**Issue by mick-scully** [CSSEGISandData/COVID-19#3860] opened 2021-03-24 20:34 UTC
Looks something is amiss with the data capture. How can we fix it? 

Happy to help, but need to be pointed in the right direction

https://data.sfgov.org/stories/s/dak2-gvuj

**Comment by CSSEGISandData** [comment] 2021-03-24 22:26
Hello,

We have identified the source of this issue and are working on a fix. Thank you for your patience.

**Comment by mick-scully** [comment] 2021-03-24 23:36
Thanks much......

**Comment by dje1591** [comment] 2021-03-25 00:35
Philadelphia, Pennsylvania has not had updated cases & deaths since 3/20/2021.

**Comment by jimgrcovid** [comment] 2021-03-25 06:51
Along with San Fransisco County, these five counties in California have zero new cases since  March 16, though relevant listed CSSE data sources seem to state otherwise:
Butte, Glenn, Yolo, Amador, Imperial

**Comment by CSSEGISandData** [comment] 2021-03-25 09:36
@dje1591 Philadelphia, Pennsylvania was patched with #3863.

@jimgrcovid all six counties are related to a source change for CDPH that hadn't been caught by our QC processes. We should have the data updated later today.

**Comment by CSSEGISandData** [comment] 2021-03-25 20:38
Hi all,

This has been resolved by PR #3873.

**Closed by CSSEGISandData** 2021-03-25 20:38 UTC

**Comment by mick-scully** [comment] 2021-03-25 20:55
Thank you for all the work you are doing!

**Comment by jimgrcovid** [comment] 2021-03-26 08:56
@CSSEGISandData

Thanks for the resolution.  _Is there a specific number/range of days that were changed_**?**

I (think) I have attached an image showing deaths per day by Calif county from March 9 '21 thru March 25 '21.
There are a few negative numbers.

Two data rows discussed:

Butte County  as of March 25:
   CSSE master zip shows two -1 days and an outlier +15 day.
   CSSE master zip shows 187 deaths.
   Butte County ( https://infogram.com/1pe66wmyjnmvkrhm66x9362kp3al60r57ex?live ) shows confirmed 177 plus 48 probable dead. (This is not a listed source for CSSE)
   I see Calif State ( https://public.tableau.com/profile/ca.open.data#!/vizhome/COVID-19CasesDashboardv2_0/CaseStatistics ) shows 187 dead.
   I'll be asking Butte County and Calif. State about the difference between 177 and 187.

Glenn County dead drops 6 on the 16th then increases 7 on the 25th.
Glenn County's ( https://www.countyofglenn.net/dept/health-human-services/public-health/covid-19 ) March 25 dead count matches CSSE master zip.  Though CSSE source site ( https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/Immunization/ncov2019.aspx )  shows 17 dead, thus listed CSSE source and CSSE master zip data do not reconcile.

_In general how are negative deaths handled by CSSE_**?**  

_Can you provide the link for the downloadable database source from Calif. State that CSSE uses_**?**  I went to CSSE source site ( https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/Immunization/ncov2019.aspx ) and could not find it.



Thank you in advance



![deathperday](https://user-images.githubusercontent.com/76698889/112600334-4c6e2b80-8dce-11eb-9072-15f91ebc97a8.jpg)
