### ISSUE TITLE
Jefferson, TX data issue on 6/22 - 505 new cases

### ISSUE THREAD

**Issue by sth-del** [CSSEGISandData/COVID-19#4276] opened 2021-06-23 13:21 UTC
Hello,

I see that Jefferson, TX reported 505 new cases on 6/22. This number is significantly higher than usual - the 14 day average of new cases is 3. Is there any insight into how many of these are current, and how many are part of a backlog?

Thanks in advance.

**Comment by CSSEGISandData** [comment] 2021-06-23 14:49
Hello,

The spike in confirmed cases is present in the Texas [time series excel](https://dshs.texas.gov/coronavirus/TexasCOVID19DailyCountyCaseCountData.xlsx) but does not have any special indication on the Texas [data notes page](https://dshs.texas.gov/coronavirus/casenotes/june2021.aspx). We'll keep investigating to try to find the reason for the spike.

**Comment by CSSEGISandData** [comment] 2021-06-25 11:52
Hello,

We've received the following communication from DSHS:

"Jefferson County cases are reported from at least two main local health departments (Beaumont and Port Arthur), ingested through our agency’s regional office, and then reported daily by our central office. It appears that Beaumont had not reported its cases between 5/3 and yesterday. However, we do not currently know the temporal distribution of these newly reported cases and can’t identify which ones would normally be identified as “older”. We are awaiting further word from the local health department and region and may edit our data once we know more about this bolus of cases."

**Comment by CSSEGISandData** [comment] 2021-07-08 20:17
Hello!

We have finally received clarity from the state regarding this issue. 482 of the 505 new cases occurred more than 14 days before 6/22. I'll close this issue now but please follow up if there are additional questions.

**Closed by CSSEGISandData** 2021-07-08 20:17 UTC
