### ISSUE TITLE
Please May you Load back all USA individual States data back.

### ISSUE THREAD

**Issue by samscodes** [CSSEGISandData/COVID-19#1675] opened 2020-03-27 08:56 UTC
Hello guys,
May you load all the USA individual States data back as it was before? It's very import to analysis data in USA based on States because for now USA has the most Confirmed Cases in the world. Other country such as China and Canada still have their individual Provinces/States why not USA?

Thank in Advance

**Comment by cipriancraciun** [comment] 2020-03-27 10:27
I have built a derived dataset based on JHU dataset, where (among other fixes and features) I also aggregate the data for US at both state and country level, and merge everything in a single dataset for easy usage:

* https://github.com/cipriancraciun/covid19-datasets
* I have described it in this issue #1281 or the readme in the repo above;

(I try as much as possible not to change the format too much, mainly I only add new rows and columns.)

**Comment by bbees** [comment] 2020-03-27 12:56
@cipriancraciun do you automatically update your derived dataset daily?

**Comment by cipriancraciun** [comment] 2020-03-27 13:01
@bbees I update the datasets immediately after JHU updates them.  (And given I have nowhere to go, it won't be much delay.)  :)

To answer you directly:
* all the data processing is automated with a `make`-like system, thus re-generating everything is a matter issuing a command and waiting;
* I could easily add a cron to do this automatically, however,
* the major issue with the JHU dataset (and what prompted me to create a derived dataset) is the "quality" and consistency of the JHU data;  for example in order to properly get the various values to the right "locations" I built an extensive lookup dictionary that solves the various inconsistencies;

Therefore, although the data is generated automatically, before I push, I do a `diff` on the resulting files (and intermediary ones if needed) to be sure nothing is "broken".

Thus to conclude:  in order to keep the data quality high, I supervise the automatic processing of data.  :)

**Comment by ShashaankV** [comment] 2020-03-27 14:40
It's important to have State and possibly County and City resolution for the US. Several issues with modeling at the Country level for the United States. For example, it's unlikely we can assume homogenous mixing and sampling for the whole US. Need this resolution and counts for a span of days, not a single snapshot. Please include Confirmed, Death, and Recovered. Would be nice to have Population Size as well. Would be great to include fraction tested and serology data when it becomes available.

**Comment by cipriancraciun** [comment] 2020-03-27 19:53
@samscodes In order to help the JHU team (which I assume are already swamped by work and issues), and to keep thing tidy, would you consider closing this issue and perhaps following #1681 which seems to be the ticket that collected all issues on this topic.

**Closed** 2020-04-25 02:30 UTC
