### ISSUE TITLE
Insight into changing values in "unassigned" and "Out of ..." rows?

### ISSUE THREAD

**Issue by DanielJWood** [CSSEGISandData/COVID-19#2055] opened 2020-04-07 20:56 UTC
Does anyone have insight into where the numbers in "unassigned" and "out of STATE" rows are coming from? I notice that they increase and decrease depending on the day, and there's no documentation that I know of that demystifies this. Here's an example, the unassigned for Washington state, which increases and decreases:

```
[...]0,0,5,0,36,65,39,0,0,0,0,151,130,146,164,145,112,51,69,67,0,125,274,274,303,344,501,483,533,648
```

**Comment by cipriancraciun** [comment] 2020-04-07 21:01
This is a duplicate of #2035 

In order to help the JHU team and keep things tidy I would suggest following that issue, and closing this one.

**Comment by troymartinhughes** [comment] 2020-06-16 07:58
@DanielJWood , I've done an analysis here that will provide some insight: https://www.linkedin.com/pulse/county-less-covid-19-how-unassigned-out-state-counties-troy-hughes

**Closed** 2020-06-16 11:13 UTC
