### ISSUE TITLE
Stat from French is broken.

### ISSUE THREAD

**Issue by Knackie** [CSSEGISandData/COVID-19#564] opened 2020-03-12 13:58 UTC
Hi,
U have country French and France, and french is not update.

**Comment by lazd** [comment] 2020-03-12 15:22
There is a `French Guiana` in the dataset, as well as `France` itself and two territories `St Martin, France`, and `Saint Barthelemy, France`. I see no issues with the data for any of those rows.

I think you should close this issue.

**Comment by JiPiBi** [comment] 2020-03-12 23:27
Please See #555 :  the issue is a bad aggregation for France

**Comment by JiPiBi** [comment] 2020-03-18 15:38
@Knackie
 at this moment,  only Martinique remains as a country, the other territories became provinces

**Closed** 2020-10-01 09:33 UTC
