### ISSUE TITLE
Where are the state- and county-level data for the US

### ISSUE THREAD

**Issue by SteveForsythe** [CSSEGISandData/COVID-19#1692] opened 2020-03-27 15:11 UTC
I haven't been able to find them.

**Comment by kuhndj67** [comment] 2020-03-27 15:19
verified that US data is missing ATM.

**Comment by cipriancraciun** [comment] 2020-03-27 15:41
The data at county level is available inside the `sse_covid_19_data/csse_covid_19_daily_reports` folder.  For state level you'll have to summarize it yourself.

----

That being said, I have built a derived dataset based on JHU dataset, where (among other fixes and features) I also aggregate the data for US at both state and country level, and merge everything in a single dataset for easy usage:

* https://github.com/cipriancraciun/covid19-datasets
* I have described it in this issue #1281 or the readme in the repo above;

(I try as much as possible not to change the format too much, mainly I only add new rows and columns.)

**Comment by cipriancraciun** [comment] 2020-03-27 19:47
@SteveForsythe In order to help the JHU team and consolidate the open issues, would you want to subscribe and follow for example #1681 and close this ticket?

**Comment by cruyffturn** [comment] 2020-03-28 10:26
You can check the NY Times dataset, which provides state wise information 

[https://github.com/nytimes/covid-19-data.](url)

**Comment by davidbau** [comment] 2020-03-29 19:26
dupe of #1505

**Closed** 2020-07-17 15:37 UTC
