### ISSUE TITLE
France confirmed incorrect for 4/4/2020: it should be 68605.

### ISSUE THREAD

**Issue by loulouOz** [CSSEGISandData/COVID-19#1982] opened 2020-04-05 01:53 UTC

**Comment by catastrop56** [comment] 2020-04-05 02:28
I agree, in file 
    time_series_covid19_confirmed_global.csv 
the line starting with
   ,France
should have column 
    4/4/2020 
replaced by 
    68605 
(instead of 89953)

**Comment by mkosunen** [comment] 2020-04-05 02:57
I Agree, but. May I ask what source you use for the data for European countries? At least There seems to be discrepanies  of daily increases between JHU nadn ECDC  data, 
and I have not figured  out to way to pick the "correct" number. 
https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

**Comment by catastrop56** [comment] 2020-04-05 05:25
Dear Marko
My comment was only about the French numbers, which I hear on TV and
humanly read from the ministry of health web page (not a file).

The ECDC address you provided has some wrong data: I read the csv only, but
it has daily increments with one day delay, i.e., the increment in cases
posted as of 04/04 is the diff between confirmed of 04/03 and 04/02.

I have not found yet a reliable and aggregated french source, but the
following one for each day seems OK. The yaml file

https://github.com/opencovid19-fr/data/blob/master/ministere-sante/2020-04-04.yaml


was posted yesterday and reads:


date: 2020-04-04
source:
nom: Ministère des Solidarités et de la Santé
# PDF confidentiel et échanges directs avec la DGS
donneesNationales:
casConfirmes: 68605
deces: 5532
decesEhpad: 2028
hospitalises: 28143
reanimation: 6838
gueris: 15438

from which you can extract confirmed (68605) and dead (5532). These
cumulated numbers. It was uploaded on 04/04 at about 22:00 french time.
If I find something better I will let you know.
All the best.
Yannick

**Comment by mael-lenoc** [comment] 2020-04-05 06:53
I agree with catastroph56. There is indeed an issue with the numbers for France.

The datasource he provided is from an official repo from the French Health department, so it's probably what you would consider the most accurate and up to date source (they update it once a day I believe).

Regarding the number of deaths, you need to add deces (5532, number of death mostly in hospitals) and decesEhpad (2208 number of deaths in nursing home, which are not being reported as fast), so that's a total of 7560 deaths to date.

**Comment by papayou66** [comment] 2020-04-05 07:06
+1 with @catastrop56

**Comment by alfkoehn** [comment] 2020-04-05 07:32
@catastrop56 thanks for the corrected numbers. It is still a very strong increase, do you happen to know what the cause for this is? (For the strong increase in number of deaths, I understood that's due to taking into account senior residences, which were neglected previously(?))

**Comment by mael-lenoc** [comment] 2020-04-05 07:47
@alfkoehn 
The increase is in fact slowly slowing down (it's still increasing, but not as fast as it was a few days ago), probably due to the fact that everyong in france is quarantined. It looks like the peak may have been reached (we'll only know for sure in a few more days though).

Regarding the number of deaths, senior residences are counted separately (that's the decesEhpad number, which is not included in the deces number). This number is only partial as not all senior residence have reported their numbers yet. The number of deaths (senior residence excluded) is stabilizing, about 500 deaths per day for the past 4 days.

**Comment by mpascariu** [comment] 2020-04-05 08:07
Yes, there must be a typo in the numbers for France. 25k new cases yesterday is not confirmed by French sources.

**Comment by brungio** [comment] 2020-04-05 08:19
Good morning all, and very sorry for intruding off-topic. Can someone please tell me why Sante Publique France doesn't release the number of recovered per region any more? Makes quite some models impossible...

**Comment by FrenchGu** [comment] 2020-04-05 09:01
>I have not found yet a reliable and aggregated french source, but the following one for each day seems OK.
> […](#)

Official French numbers are here, updated every day : https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/infection-au-nouveau-coronavirus-sars-cov-2-covid-19-france-et-monde

**Comment by RomaricGravet** [comment] 2020-04-05 09:13
> Good morning all, and very sorry for intruding off-topic. Can someone please tell me why Sante Publique France doesn't release the number of recovered per region any more? Makes quite some models impossible...

Hi,
You can find a more precise report on Sante Publique France portal, with the evolution of the number of case region by region. But this report is only update one times per week.
https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/documents/bulletin-national/covid-19-point-epidemiologique-du-2-avril-2020

**Comment by brungio** [comment] 2020-04-05 14:19
Hi.

thank you @RomaricGravet and @FrenchGu for your answer. What I am after is the total number of cases per region. This likely includes also the positive tests with no symptoms. This record disappeared form the reports of Sante Publique France in March. The only number we have is for all of France.

Apologies again for intruding in this thread. And thank you for your help.

**Comment by RomaricGravet** [comment] 2020-04-05 14:27
Hi @brungio 
I'm thinking about it, you might have this information on the site data.gouv.fr, it gathers raw data on the epidemic and at first glance there is data on screening lab by lab.
https://www.data.gouv.fr/fr/organizations/sante-publique-france/
Sorry, it's only in french, as usual in France XD
BR,

**Comment by FrenchGu** [comment] 2020-04-05 19:01
Hello @CSSEGISandData , please correct confirmed cases France 04/04/2020, graphs are ridiculous with a 20k+ mistake... thank you

**Comment by martinedoesgis** [comment] 2020-04-05 21:09
https://www.gouvernement.fr/info-coronavirus/carte-et-donnees

**Comment by mkosunen** [comment] 2020-04-06 03:13
I think someone needs to make a pull request in order to get this corrected. 

French data is becoming increasingly invalid. Started on April 2nd ( #1926 ) I suggest that the persons that have the accurate data file  pull requst and document where they are geiitng it. It seems there is a systematic error obtaining the data.

Related issues
#1926

**Comment by FrenchGu** [comment] 2020-04-06 07:34
According to Le Monde french journal, @CSSEGISandData 's count for France confirmed cases 4/4/20 includes the 22,361 **potential** cases listed in the nursing home (as well as a double count of cases in the ultra-marine territories) which are not considered in [french official data](https://dashboard.covid19.data.gouv.fr/). They also announce they will now use official french Santé Publique France data instead of JHU data for France confirmed cases and deaths.  

Source : https://www.lemonde.fr/planete/live/2020/04/05/coronavirus-aux-etats-unis-trump-annonce-une-periode-qui-va-etre-vraiment-horrible_6035613_3244.html?highlight=1187488818

**Comment by mkosunen** [comment] 2020-04-06 08:05
Any idea what source @CSSEGISandData uses for the French values? Will this problem be repeated?

**Comment by RomaricGravet** [comment] 2020-04-06 09:27
@FrenchGu I think the worst thing in this case is the fact that, in addition to changing in the middle of a series of data the definition of said data without any mention of this change, nor of the motivations for this change, the said motivations for this change are based on rumor and testimony. If a change in the definition of the case is to be made, it must be made on the basis of solid arguments from the scientific community.

**Comment by RomaricGravet** [comment] 2020-04-06 09:30
> Any idea what source @CSSEGISandData uses for the French values? Will this problem be repeated?

@mkosunen Yes, I have of course an idea for the french data provider : Santé Publique France (https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/infection-au-nouveau-coronavirus-sars-cov-2-covid-19-france-et-monde)
It's the official French institute in charge of monitoring epidemics in France. It's the most legitimate source for this kind of information.

**Comment by FrenchGu** [comment] 2020-04-06 09:45
@RomaricGravet 
@mkosunen asked what source uses @CSSEGISandData to get their wrong data (aka not the official ones). 
I somehow understand what they tried to do. France started to add deaths in nursing home to the total deaths count. This changes the ratio between deaths and confirmed cases. I suppose that’s why they’ve added potential cases listed in the nursing homes (I don’t know from what source) to the total of confirmed cases. 
Anyway, confirmed cases in France is a non relevant far from reality count because only severe cases are tested in hospitals.

**Comment by RomaricGravet** [comment] 2020-04-06 10:40
@FrenchGu 
Indeed I somewhat misunderstood the question asked by @mkosunen.
Then, of course, the number of cases is underestimated, but I do not think that France is the only country in this case, and, more importantly, I do not think that a suspicious case can be considered a reported case. A suspect case is a person with symptoms similar to VIDOC19 , there is no evidence that they are actually VDRSA-VOC-2 infection. So I'm sorry but I maintain my objection, we cannot change the case definition without a strong argument.
In fact, I would like to point out that Professor Salomon, Director General of Public Health, gives the number of "SOS médecin" interventions every day for suspected cases of COVID19, but he clearly states that these are suspect cases, not confirmed cases.

**Comment by FrenchGu** [comment] 2020-04-06 10:59
@RomaricGravet i agree and that was the point of my previous comments : let’s stick to Santé Publique France official confirmed cases count

**Comment by RomaricGravet** [comment] 2020-04-06 11:01
@FrenchGu 
+1000 :)

**Comment by blisx264** [comment] 2020-04-06 11:29
> I Agree, but. May I ask what source you use for the data for European countries? At least There seems to be discrepanies of daily increases between JHU nadn ECDC data,
> and I have not figured out to way to pick the "correct" number.
> https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

I agree, there are varying discrepancies, many are due to lack of reporting, Im checking all health departments in Australia and while there are small margins of error at times,  a margin of error should be tolerated considering the situation

**Comment by blisx264** [comment] 2020-04-06 11:30
> @RomaricGravet i agree and that was the point of my previous comments : let’s stick to Santé Publique France official confirmed cases count

So where's the link?

**Comment by mkosunen** [comment] 2020-04-06 13:26
So, we still do not know from where the +20k cases were fetched from  and if that mistake/feature/improvement can happen again? (+we still  do not know if the fix will be eventually merged) 

I think minor discrepancies are OK, but +20k is a bit too much just to be fetched from somewhere. :)

**Comment by martinedoesgis** [comment] 2020-04-06 13:34
This appears now on a lot of others websites like worldometers, I don't know what is the original error (if JHU fetches from worldomoters or the other way) but that shows the limitations of having a single source of data replicated everywhere.
https://www.worldometers.info/coronavirus/country/france/

**Comment by mkosunen** [comment] 2020-04-06 13:45
@martinedoesgis I think having one source of data is great, but 1) For some reason that one source of data is now a US-based private university (which is very OK, but should preferably be WHO or some global official agency)  2) The data is invalid. (Should be corrected) 

Would be way more difficult to fix 1000 incorrect, incomparable sources of data :)

**Comment by mkosunen** [comment] 2020-04-06 13:52
In https://www.worldometers.info/coronavirus/country/france/

It says:
April 4 (GMT)

    7788 new cases and 1053 new deaths in France [source]

" France: on April 3 the French Government reported 17,827 additional cases and 532 additional deaths from nursing homes that had not been reported previously. On April 2, it had reported 884 additional deaths."

What might be the truth? Is this increase officially reported by the French government or not?

**Comment by martinedoesgis** [comment] 2020-04-06 14:03
@mkosunen  : These 17827 are suspected cases according to the government, not confirmed, due to the lack of testing in nursing homes in France. If we add them to the total then the number is correct but in that case you have to add all the suspected cases all other the world to have consistency in the data.

**Comment by mpascariu** [comment] 2020-04-06 14:03
(found on Worldometer:

NOTE ON FRANCE DATA:

On April 2, France reported 884 additional deaths that have occurred in nursing homes over the past days and weeks [ [source](https://translate.googleusercontent.com/translate_c?anno=2&depth=1&hl=fr&rurl=translate.google.com&sl=en&sp=nmt4&tl=fr&u=https%3A%2F%2Fwww.reuters.com%2Farticle%2Fus-health-coronavirus-france-toll%2Ffrances-coronavirus-death-toll-jumps-to-nearly-5400-as-nursing-homes-included-idUSKBN21K31I&usg=ALkJrhjtj4ADURdFhzRhSxe8AKNbYbrCMA) ]. The French Government did not include these deaths in their official count , as their count only takes into consideration deaths of hospitalized patients. Following international standards of correct inclusion, our statistics will include these deaths, and will add them to the April 2, 2020 count following the attribution criteria of date of report .

If and when the French government determines and communicates the correct distribution of these additional deaths over time, we will adjust the historical data accordingly. A similar issue took place on February 12, when China reported an additional 13,332 new cases in a single day due to a change in how cases were diagnosed and reported in Hubei.

**Comment by mkosunen** [comment] 2020-04-06 14:17
After all, I'm fine with any number the French think is the correct one,  but it should preferably be one number. Multiple numbers are ok too, if the dirreference is a bit less that 20k.  :)

**Comment by mkosunen** [comment] 2020-04-06 14:20
Should I close the pull request, or should we wait?

**Comment by martinedoesgis** [comment] 2020-04-06 14:24
The problem the misunderstanding comes from the fact is that they considered that the cases in the nursing homes were new cases (quote from worldometers : on April 3 the French Government reported 17,827 **additional** cases). If you listen to the official report, they never say **new** cases, just that they are XXX cases in the nursing houses, but that were probably already part of the total. The new info is really the death in nursing homes that were not counted.
Now on the official data they do the difference for the death between hospitals and nursing homes. They would also do the same for the cases if it was two different countings (https://www.gouvernement.fr/info-coronavirus/carte-et-donnees).
Well, all official sources and news papers in France don't add those 25k in the counting so there's definitely something strange in the JHU data.

**Comment by Clumpton** [comment] 2020-04-07 02:50
An important aspect of the apparent discrepancy between Official French stats and the JHU data is the creation of unnecessary paranoia among the French populace. The government is already being accused of multiple cover-ups (masks, gowns etc.), so neither the govt. nor the people need apparently "hidden" cases being added to the mix. Please consider using  only the data from https://www.gouvernement.fr/info-coronavirus/carte-et-donnees

**Comment by alfkoehn** [comment] 2020-04-18 06:51
For the date this issue is about, the number has been fixed, see updated [1].

[1] https://github.com/CSSEGISandData/COVID-19/issues/2094

**Closed** 2020-04-18 07:08 UTC
