### ISSUE TITLE
Other locations - 1300 - Is this correct?

### ISSUE THREAD

**Issue by Shane073** [CSSEGISandData/COVID-19#70] opened 2020-02-17 09:41 UTC
Currently on the https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6 website. Other locations has jumped from 780 to 1300 on the graph in the bottom right corner. Yet when you calculate the confirmed cases it gets to 803, it doesn't get any where near 1300. Is the data in the "confirmed Cases by Country/Region" yet to be updated? Or is the other locations graph in the bottom right corner incorrect? Thanks for your help.
![john hopkins csse - 17 2 20  - data inconsistent](https://user-images.githubusercontent.com/36460101/74641706-d6a89100-51c5-11ea-87ef-01b97e885d66.png)

**Comment by ricir** [comment] 2020-02-17 12:19
I have the same question.

**Comment by iceweasel1** [comment] 2020-02-17 13:16
Mhh, my screenshot is from now, but maybe there was a short error in the system before, which showed you the wrong numbers.

![Bildschirmfoto vom 2020-02-17 14-15-02](https://user-images.githubusercontent.com/49625256/74657211-0a68c400-5190-11ea-8811-099bcf850f86.png)

**Comment by ricir** [comment] 2020-02-17 13:22
![image](https://user-images.githubusercontent.com/52215524/74657467-9844af00-5190-11ea-9467-44b92097f746.png)
It seems to me tat it is still showing 1..3k by hovering on the last point.

**Comment by nimrodvern** [comment] 2020-02-17 13:31
![Screenshot_20200217-043341](https://user-images.githubusercontent.com/61150701/74658146-46336780-5157-11ea-962e-42fd4d587187.png)

Easier to see if you x-out mainland China and recovered in the legend.

**Comment by bjarkimg** [comment] 2020-02-17 14:20
Why this lag in the github data vs official chart?
This gives false hope if current date is only half reported... IMO

http://bit.ly/38qeMbz <- PowerBI with github data

![image](https://user-images.githubusercontent.com/1289419/74661691-59165e00-5190-11ea-802e-65011f0ca58c.png)

**Comment by ultima-thule-design** [comment] 2020-02-17 17:17
It seems that today the data of the Diamond Princess infected has been counted twice. If you add the infected by country you get 71448, if you then re-sum the infected of Diamond (454) you get 71902. Same goes if you calculate the new contagions of today, 108 China, 114 Other Countries, re adding up all the infected of Diamon (454) you arrive at the figure of 676.

**Comment by iceweasel1** [comment] 2020-02-17 18:13
Guys, you're right. It's the same for me. Let's see what the reason is.



> Mhh, my screenshot is from now (14.17 Uhr / 2.17 pm, German time CET), but maybe there was a short error in the system before, which showed you the wrong numbers.
> 
> ![Bildschirmfoto vom 2020-02-17 14-15-02](https://user-images.githubusercontent.com/49625256/74657211-0a68c400-5190-11ea-8811-099bcf850f86.png)

**Comment by ricir** [comment] 2020-02-17 18:36
A screenshot from the count for City/State/Prov:
![image](https://user-images.githubusercontent.com/52215524/74678925-af999180-51bc-11ea-8a34-a9fdfd0efdd3.png)
As you can see, there is "Diamond Princess" with 454 and "Others" with 454

**Comment by zacthompson** [comment] 2020-02-17 18:55
This is as small of a query as I could narrow it down to. Definitely a data problem.

https://services1.arcgis.com/0MSEUqKaxRlEPj5g/ArcGIS/rest/services/Coronavirus_2019_nCoV_Cases/FeatureServer/1/query?f=json&where=Country_Region%20in%20(%27Diamond%20Princess%27,%27Others%27)&returnGeometry=false&outFields=Country_Region,Province_State,Confirmed&outSR=102100&cacheHint=true

**Comment by iceweasel1** [comment] 2020-02-17 20:16
@zacthompson A small problem with a big impact ;-)

**Comment by dawenx** [comment] 2020-02-17 21:20
The number on our tool (http://ncov.bii.virginia.edu/dashboard/ ) is correct, but we don’t update that often (our last update was this morning at 10am EDT). We are committed to update every day after China releases new data which is around 10pm EDT.

**Comment by CSSEGISandData** [comment] 2020-02-17 23:28
Hey there! We have fixed this technical hiccup in the dashboard. Thanks so much for your reminder. We will also correct the csv files if this duplicate is found.

**Comment by gabrielbauman** [comment] 2020-02-18 07:48
> Hey there! We have fixed this technical hiccup in the dashboard. Thanks so much for your reminder. We will also correct the csv files if this duplicate is found.

You should close the issues that you have addressed.

**Closed** 2020-03-09 16:29 UTC
