### ISSUE TITLE
Taiwan was taken off list, we are a free democracy, not part of china

### ISSUE THREAD

**Issue by ByronLian** [CSSEGISandData/COVID-19#406] opened 2020-03-11 03:01 UTC
Please fix this asap
>> https://github.com/CSSEGISandData/COVID-19/issues/404

**Comment by eugene-yang** [comment] 2020-03-11 03:09
Looks like they are having some issues with the latest update, which includes city/state breakdown information in the daily report and time series files. 
A lot of them have been taken care of by #399. 

Currently, in this repository, Taiwan is marked as `Taiwan,Taipei and environs`, which is inconsistent with the map.
![image](https://user-images.githubusercontent.com/15350619/76378447-c34f9800-6323-11ea-9ff5-af2dd446d4b5.png)
Search result: https://github.com/CSSEGISandData/COVID-19/search?q=Taipei&unscoped_q=Taipei&fbclid=IwAR0C3g04ksSivSUoHUC6Umk8iiYTAFZV6Xe8Y-grx6knt3klBWlA-by0kSw

Let's give them some time to fix these issues. And @CSSEGISandData please let us know if there's anything we can help with.

**Comment by julietchen** [comment] 2020-03-11 03:15
They've now removed Taiwan from the country/region list and stuck it in the state/province list only under China. I'm hoping this gets fixed soon. It's extremely upsetting.

**Comment by ButTaiwan** [comment] 2020-03-11 03:15
@eugene-yang  They just DO EVIL. #404

**Comment by kiang** [comment] 2020-03-11 03:18
Just sent a PR for this
https://github.com/CSSEGISandData/COVID-19/pull/408

**Comment by eugene-yang** [comment] 2020-03-11 03:21
@ButTaiwan  not sure what kind of standard they are following. 
The web version and what we see in this repo are not consistent as well. 
Already sent an email to Professor Lauren Gardner at JHU regarding this issue.

**Comment by etbb** [comment] 2020-03-11 03:25
@eugene-yang they said they're following WHO report standard. Although I hope they'll come to their senses eventually, it seems unlikely to happen.

**Comment by kiang** [comment] 2020-03-11 03:28
Message from MOFA Taiwan:
"@WHO, what's wrong with you? First you called us "Taiwan, China," then you changed to "Taipei." You misreported the confirmed cases, & now you call us "Taipei & Environs." Look! Taiwan is #Taiwan & not any part of the #PRC. JW"

https://twitter.com/MOFA_Taiwan/status/1225261907084361728

**Comment by eugene-yang** [comment] 2020-03-11 03:29
FYI -- the data source 
https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200310-sitrep-50-covid-19.pdf?sfvrsn=55e904fb_2

**Comment by julietchen** [comment] 2020-03-11 03:46
Okay -- so this is because of the WHO. But this website is being viewed by **so many** people around the world. People (scientists) at work are sharing it on slack and news articles are linking to it. This isn't something they should take lightly -- especially in light of Taiwan's handling of the situation. @eugene-yang props for the calm call for giving them fix it, but it definitely created a lot of anxiety in me that I did not expect. Talk about a lesson in Ethics in Engineering ...

**Comment by Eclipsed830** [comment] 2020-03-11 03:57
I also noticed this issue earlier this morning. Taiwan isn't a member of the WHO, so it would make very little sense to use WHO naming conventions on a non-member state.

We need to be clear, the Chinese (PRC) government does not represent the Taiwanese government or CDC. China has zero effective authority or jurisdiction over Taiwan. Taking this position is very dangerous for many different reasons and I am disappointed John Hopkins would spread this type of misinformation. Hopefully this is just an error and will be fixed shortly.

**Comment by benjenq** [comment] 2020-03-11 04:00
WHO has become a part of China... right?

**Comment by WinnieHappyOrg** [comment] 2020-03-11 04:01
It's a pity that scientific data has also been politicized.

**Comment by ByronLian** [comment] 2020-03-11 04:10
> FYI -- the data source
> https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200310-sitrep-50-covid-19.pdf?sfvrsn=55e904fb_2

They made a mistakes in the previous issue https://github.com/CSSEGISandData/COVID-19/issues/404

As a researcher, they can not just said "We are following the WHO report standard. Thanks!" . They should always put a question mark on everything, otherwise why we need to do the research ? If this is the way that this organization did for any research then we should put a question mark on their quality.

@CSSEGISandData , @eugene-yang gave a good example for you guys.

**Comment by eugene-yang** [comment] 2020-03-11 04:23
I would rather take a slightly different angle. 

As this is a scientific project([paper published](https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30120-1/fulltext)), the most important purpose should be getting the right information out and provide common ground for further research as well as decision making. 

Although there are political debates and subtle cross-strait relationships, I do not think this should be one of the reasons for making such a decision in a research paper. The categorization of items in a research paper should be backed with scientific reasons such as interpretability or certain property. 

In this specific case, the purpose of providing statistical information on the number of cases in different country/region/state/province/etc is to measure the risk of different areas and how effective the actions each government takes. Marking Taiwan as part of China, despite all the political reasons, provide very misleading information to everyone reading the map -- what the Chinese government is doing has an effect on Taiwan -- which is entirely wrong. 

I do not want to put it as a political issue -- because it is NOT! This is the responsibility of being a scientist and research. We have the responsibility to communicate the information and knowledge accurately, effectively and efficiently! 

@CSSEGISandData @hongru94 @enshengdong I hope you have the right mindset to handle this issue. And I am more than happy to discuss this topic in further detail.

**Comment by Faratia** [comment] 2020-03-11 04:25
I think Hong Kong and Macau were also taken off the panel on the left, listing the full name of Iran was also really unnecessary.
I don't understand why suddenly the whole thing became so political.

**Comment by Eclipsed830** [comment] 2020-03-11 04:27
> @eugene-yang they said they're following WHO report standard. Although I hope they'll come to their senses eventually, it seems unlikely to happen.

Where did they say they're following the WHO? [According to this article the issue has been discovered and will be fixed shortly](https://www.axios.com/johns-hopkins-coronavirus-map-taiwan-china-5c461906-4f1c-42e7-b78e-a4b43f4520ab.html):

> When contacted by Axios, Lauren Gardner, an associate professor of civil and systems engineering at JHU who directs the map project, said that they had just caught the change and would be changing it back to "Taiwan" immediately.

**Comment by eugene-yang** [comment] 2020-03-11 04:27
@Eclipsed830 #404

**Comment by Clifford-Yen** [comment] 2020-03-11 04:29
> In this specific case, the purpose of providing statistical information on the number of cases in different country/region/state/province/etc is to measure the risk of different areas and how effective the actions each government takes. Marking Taiwan as part of China, despite all the political reasons, provide very misleading information to everyone reading the map -- what the Chinese government is doing has an effect on Taiwan -- which is entirely wrong.

I totally agree with that. The reason why Taiwan can be so strong and keep standing in this fight is just because we are not part of China. Making us as part of China provides a the wrong information to the world.

**Comment by etbb** [comment] 2020-03-11 04:29
The concept of categorization itself is exactly political.

**Comment by ohbriansung** [comment] 2020-03-11 04:32
<img width="1023" alt="Screen Shot 2020-03-10 at 21 01 21" src="https://user-images.githubusercontent.com/19147213/76382645-a2cd1100-6316-11ea-9246-f887ea8824f7.png">

**Comment by duncanhsieh** [comment] 2020-03-11 04:35
If you can go to Taiwan with a China visa please write down "Taiwan, China", else please recover the "Taiwan, Taiwan"

**Comment by vincentlaucy** [comment] 2020-03-11 04:38
Does that imply Taiwan is doing so much better than China so its numbers not worth being included in the list?

**Comment by eugene-yang** [comment] 2020-03-11 04:42
@vincentlaucy Not exactly. Should we include North Korea into China just because they are doing better/worse than China? 

A hierarchical structure should have its own meaning. As Taiwan is not operated by the Chinese government, the measure the authority takes and the risk of these two areas are very different. It is beyond the political debate but a matter of the integrity and responsibility of a piece of research.

**Comment by Eclipsed830** [comment] 2020-03-11 04:45
> @Eclipsed830 #404
> And you can look at what the author of that article tweeted
> https://twitter.com/BethanyAllenEbr/status/1237511921798021120?fbclid=IwAR1r8Le0Af7-6mMgdxIrXvKQqRZ_TP7AI_uClFbPhFhTe-F8Z8qasgJ12ik
> 
> Gives this story a slight twist.

Wow... That is both shocking and disappointing. :(

**Comment by lipuyeh** [comment] 2020-03-11 06:29
Please fix this asap

**Comment by a2d8a4v** [comment] 2020-03-11 07:08
Please fix this asap.
The medical system in Taiwan is 100% independent from mainland China, and Taiwan take 100% different action to coronavirus, there is no reason to make Taiwan be one of the providence under China mainland

**Comment by piyueh** [comment] 2020-03-11 07:14
The first two authors of the [paper](https://doi.org/10.1016/S1473-3099(20)30120-1) may be Chinese. What are we expecting ..

**Comment by KevinCayenne** [comment] 2020-03-11 08:07
Please fix this asap! Thank you!

**Comment by jeromaxyu** [comment] 2020-03-11 08:28
Hong Kong and Macau had totally different system as well, should separate, otherwise why should we use your platform, we just switch back that no-credible WHO again

**Comment by akikase** [comment] 2020-03-11 09:09
@CSSEGISandData Please act like a professional and a researcher with an independent mind.
If you made the decision of taking off Taiwan, please give the public a good reason other than 'following the WHO'.
Take the leadership. Make good judgement.

**Comment by weasellin** [comment] 2020-03-11 10:49
@CSSEGISandData
What we taiwanese people hope is very simple,
to be respected, and don't put our country under another one.

**Comment by QQQ-YT** [comment] 2020-03-11 11:29
Taiwan is an integral part of China.
Any attempt to split China is ignorant.
Obviously Github is the logical side.

**Comment by Eclipsed830** [comment] 2020-03-11 11:46
[This issue just made Reuters...](https://www.reuters.com/article/us-health-coronavirus-taiwan-university/taiwan-protests-as-top-u-s-university-labels-island-part-of-china-on-virus-map-idUSKBN20Y0NK) but the last sentence is the most important key point that I hope @CSSEGISandData understands:

>The island is not governed in any way by Beijing, and Beijing has no direct say in its health policy or how it handles the virus.

**Comment by Johnny850807** [comment] 2020-03-11 12:24
@CSSEGISandData Please stand by the side of justice, do Taiwan a favor, every Taiwanese will appreciate. And, this is a truth, Taiwan is an independent democracy, so we argue for the truth, not for the benefit.

**Comment by SeanHung06** [comment] 2020-03-11 13:10
Please  fix this ASAP Taiwan is an Independent Country and different from CHINA

**Comment by guan0975** [comment] 2020-03-11 13:41
Taiwan has its own health policies dealing with COVID-19, which is totally different from that of mainland china. It seems to be quite misleading to label Taiwan as a part of China, as it conveys the wrong information about the current situation of Wuhan coronavirus outbreak.

**Comment by may21101123** [comment] 2020-03-11 14:35
Taiwan is not part of China and we’re doing pretty well on the epidemic control, despite the fact that we’re excluded from the WHO.

**Comment by CSSEGISandData** [comment] 2020-03-11 14:38
please see issue #482

**Closed by CSSEGISandData** 2020-03-11 14:38 UTC

**Comment by eugene-yang** [comment] 2020-03-11 20:33
For people here, they have addressed this issue. 
Please give them some credit :) 
https://github.com/CSSEGISandData/COVID-19/issues/482#issuecomment-597862609

**Comment by derekdylu** [comment] 2020-03-12 18:08
support Taiwan
