### ISSUE TITLE
New official sources for Malaysia data

### ISSUE THREAD

**Issue by 30one** [CSSEGISandData/COVID-19#4431] opened 2021-07-27 05:22 UTC
Malaysia's government just launched GitHub repos which contain raw data for cases and vaccinations in each state. Could these be added as sources?

Announcement: https://covid-19.moh.gov.my/semasa-kkm/2021/07/moh-open-sourcing-extremely-rich-data-on-the-pandemic-at-github

Ministry of Health:
https://covid-19.moh.gov.my/terkini
https://github.com/MoH-Malaysia/covid19-public

COVID-19 Immunisation Task Force:
https://www.vaksincovid.gov.my/en/statistics/
https://github.com/CITF-Malaysia/citf-public

Thanks!

**Comment by CSSEGISandData** [comment] 2021-07-27 14:13
Duplicate of #4419.

**Closed by CSSEGISandData** 2021-07-27 14:13 UTC
