### ISSUE TITLE
Please, fix this dataset or stop posting it

### ISSUE THREAD

**Issue by analyzewithpower** [CSSEGISandData/COVID-19#1150] opened 2020-03-21 03:30 UTC
This is sad. It is difficult to believe that these are unintended mistakes. Every single day, there is something wrong with this dataset, I wish I knew who we could report this to. Every reporter out there is praising JHU for posting this data, well, that praise would quickly disappear if they knew that this data is inconsistent and inaccurate. 

The number one group of people affected by these 'innocent mistakes' is the analyst community. If we report on information from a 'trustworthy' source and it turns out to be wrong, we are directly affected, people stop trusting our reports and turn back to the big guy. 

This affects the analyst community's credibility and hence our careers since these issues hinder us from producing a report that is consistent, reliable, and free of errors.

Please, stop producing this dataset if it's going to be wrong. That way, you can at least be honest and not continue being credited for providing information to the public that is actually wrong. 

I offer my assistance to help the university put together an accurate dataset. Please, let us know how we can help.

**Comment by gtestgit** [comment] 2020-03-21 03:55
Agreed.  In the BI Data Science world...we call this garbage in, garbage out. It really needs to be corrected or shut it down as it’s misleading and gives people the opportunity to make false assumptions, let alone useless in ML, AI. I appreciate the effort. However it’s useless, I wouldn’t present this to make business decisions let alone health decisions that could cost people their lives.

You have “cleaner” data if the dashboard is to be believed, just extract from the source the dashboard is using.  I can’t believe it’s using the posted CSV files.

**Comment by analyzewithpower** [comment] 2020-03-21 03:58
Exactly. Just an export from that dashboard and all these issues would go away!

**Comment by gohkokhan** [comment] 2020-03-21 04:18
True, I've been maintaining my dashboard every day, the inconsistent in the data is too frequent nowadays. I expected a slow update with accurate data. Quality is more important than quantity (the frequency of the data updated) in this case.

**Comment by gtestgit** [comment] 2020-03-21 04:32
Ok. Just to help out people in this thread. This data seems to be Day -1. Able to get clean csv data. So you won't get intra day, but the data looks clean and accurate.  Couple options to download.  I trust Tableau as a leader in BI space. https://www.tableau.com/covid-19-coronavirus-data-resources

**Comment by dhmacq** [comment] 2020-03-21 06:51
Perhaps, but one wonders how many error reports are like those of issues #1154 and #1155, in which the problem was not with the data, but was (I am convinced) due to comparing data with different update schedules.

**Comment by tbone-bts** [comment] 2020-03-21 06:56
@gtestgit Thanks for the Tableau link. Looks pretty good, although unfortunately it appears they don't have county level data. Unless I'm missing something.

**Comment by benjyz** [comment] 2020-03-21 09:06
@analyzewithpower alternatives? I've started contributing to this open effort https://github.com/covid19-data/covid19-data

**Comment by JiPiBi** [comment] 2020-03-21 10:08
@benjyz 
In fact the link you gave is working with data from ECDC , they said they stop to work with WHO from 19th of March (I didnt go through the reasons ) 
I will try to get ECDC data to see if interesting

**Comment by baryluk** [comment] 2020-03-21 12:40
Also, it is worth marking in the UI on the left, about country data which is known to be inaccurate / or with mistakes, or outdated (>36h from the last update).

**Comment by baryluk** [comment] 2020-03-21 12:42
I think splitting the data into separate files per-country, and making data in rows for each day, would make it easier to contribute, as it will be easier to see actual data, and make independent merges with updates and fixes.

Then a simple tool can create merged data files if needed.

**Comment by analyzewithpower** [comment] 2020-03-21 15:35
> @analyzewithpower alternatives? I've started contributing to this open effort https://github.com/covid19-data/covid19-data

Good morning :)

I am creating a dataset using worldometer and will post it. It is clean, the issue is that there is no historical data.

**Comment by AdamDanischewski** [comment] 2020-03-21 16:31
I was able to hack together a URL that seems to pull the data direct from arcgis in realtime, use it until it breaks - let me know:
[https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/1/query?f=json&where=(Confirmed%20%3E%200)%20AND%20(Deaths%3E0)&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Deaths%20desc%2CCountry_Region%20asc%2CProvince_State%20asc&outSR=102100&resultOffset=0&resultRecordCount=250&cacheHint=true](url)

You will be able to find the latest working url here: 
[https://scriptsandoneliners.blogspot.com/2020/03/covid-19-data-tracking.html](url)

**Comment by analyzewithpower** [comment] 2020-03-21 22:42
> I was able to hack together a URL that seems to pull the data direct from arcgis in realtime, use it until it breaks - let me know:
> [https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/1/query?f=json&where=(Confirmed%20%3E%200)%20AND%20(Deaths%3E0)&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Deaths%20desc%2CCountry_Region%20asc%2CProvince_State%20asc&outSR=102100&resultOffset=0&resultRecordCount=250&cacheHint=true](url)
> 
> You will be able to find the latest working url here:
> [https://scriptsandoneliners.blogspot.com/2020/03/covid-19-data-tracking.html](url)

I am going to give it a try now!!

**Comment by analyzewithpower** [comment] 2020-03-22 03:28
> Ok. Just to help out people in this thread. This data seems to be Day -1. Able to get clean csv data. So you won't get intra day, but the data looks clean and accurate. Couple options to download. I trust Tableau as a leader in BI space. https://www.tableau.com/covid-19-coronavirus-data-resources

I think they are using this data set. There's no recovered data since 3/18/2020.

![image](https://user-images.githubusercontent.com/61880866/77241652-9b85ed00-6bcb-11ea-9212-95af2852d759.png)

**Comment by benjyz** [comment] 2020-03-22 04:46
@analyzewithpower I wrote scraper for worldometer you can find it here
https://github.com/covid19-data/covid19-data/blob/master/data_sources/worldometer/worldometer_scraper.py

is worldometer a primary source though?

**Comment by analyzewithpower** [comment] 2020-03-22 05:26
> @analyzewithpower I wrote scraper for worldometer you can find it here
> https://github.com/covid19-data/covid19-data/blob/master/data_sources/worldometer/worldometer_scraper.py
> 
> is worldometer a primary source though?

OMG you have historical data!!! 
I can't seem to get it to work :( :(

**Comment by benjyz** [comment] 2020-03-22 05:31
via webarchive. this repo has historical data https://github.com/covid19-data/covid19-data

example in observable how to pull the JSON https://observablehq.com/@benjyz/covid-chart-alpha

**Closed** 2020-12-28 16:58 UTC
