### ISSUE TITLE
Hampden, Mass.  24,863 increase overnight?

### ISSUE THREAD

**Issue by RetiredGeologist** [CSSEGISandData/COVID-19#4097] opened 2021-05-18 10:15 UTC
Just confirming if Hampden, Massachusetts over nights increase is a data bust or backlog issue? ...  Number of cases went from 51,771 to 76,634.?

Thanks

**Comment by anthonydb** [comment] 2021-05-18 10:20
Also checking on this. MA state dashboard notes 299 new cases for 5/17/21 for the state: https://www.mass.gov/info-details/covid-19-response-reporting

JHU is reporting 25,130 for 5/17/21.

**Comment by jeremydratcliff** [comment] 2021-05-18 10:42
Hello,

Thank you both for the message. We're still seeing this number reported on the Massachusetts dashboard (see screenshot below). We're going to make the action to hold the previous county level total stale until we have more information from the state.

<img width="745" alt="Hampden_cases" src="https://user-images.githubusercontent.com/62674748/118637744-0c279a00-b7ce-11eb-91eb-07415617b191.png">

**Comment by CSSEGISandData** [comment] 2021-05-18 10:44
Hello,

Thank you both for the message. We're still seeing this number reported on the Massachusetts dashboard (see screenshot below). We're going to make the action to hold the previous county level total stale until we have more information from the state.

<img width="745" alt="Hampden_cases" src="https://user-images.githubusercontent.com/62674748/118637744-0c279a00-b7ce-11eb-91eb-07415617b191.png">

**Comment by ddesroches** [comment] 2021-05-18 14:52
It looks like someone copied the confirmed cases from Worcester county to Hampden. Worcester is much larger and 76k is right for them. Hampden shows 32 "new" cases for yesterday.

**Comment by CSSEGISandData** [comment] 2021-05-19 16:24
The update to the MA dashboard yesterday cleared this issue (and confirmed @ddesroches' hypothesis). We have not received a response from MA to correct the 5/17 data. However, their dashboard includes "new confirmed cases" as well as "total confirmed cases", so we have been able to work backwards to calculate the appropriate total. This was fixed in #4102.

**Closed by CSSEGISandData** 2021-05-19 16:24 UTC
