### ISSUE TITLE
Unusual surge in Netherlands’ deaths  (23k to 833k)

### ISSUE THREAD

**Issue by miotomita** [CSSEGISandData/COVID-19#6438] opened 2023-01-05 06:03 UTC
consequently the global death toll rose +812k  from January 3 to January 4

**Comment by CSSEGISandData** [comment] 2023-01-05 09:18
Thank you for the notification. We've identified the cause of this issue. Our live data will be corrected shortly and our historical data later on today. I will close this issue once both corrections are live. Apologies for the disruption.

**Comment by albertsun** [comment] 2023-01-05 16:42
Hi @CSSEGISandData just checking in to see when this data might be updated - I see the commit in this repo updating the data, but not in the ArcGIS dashboard yet.

**Comment by CSSEGISandData** [comment] 2023-01-05 18:18
Hi @albertsun - ArcGIS dashboard should be displaying the correct data now. Apologies for the trouble.

**Closed by CSSEGISandData** 2023-01-05 18:18 UTC
