### ISSUE TITLE
Data issues in time_series_covid19_recovered_global.csv

### ISSUE THREAD

**Issue by ShubhamGupta9582** [CSSEGISandData/COVID-19#1600] opened 2020-03-26 08:48 UTC
Hi guys, 
thank you so much for your efforts to make the data available for us on regular basis.
I have found some issues in COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv file, listing down below. it would be great if you look at this and resolve in next updation of the data.

1) the major one is no. of records in table is only for 234 rows in recovered csv but in confirmed and death csv the rows are 246. would you please make the data available for all the countries and states in recovered csv which you are providing in confirmed and death csv's.
2) missing data for 3/25/2020.
3) date format is not same as confirmed csv & deaths csv.

**Comment by JiPiBi** [comment] 2020-03-26 09:34
Thanks to warn that recovered series came back 
I only have to uncomment my code ...

**Comment by bldevries** [comment] 2020-03-26 10:06
This data set is amazing! Many thanks!

To be more specific on point 3:
- In recovered timeseries the date is formatted as: X/X/2020
- In deaths and confirmed timeseries it is formatted as: X/X/20

**Comment by downFast** [comment] 2020-03-26 10:17
> This data set is amazing! Many thanks!
> 
> To be more specific on point 3:
> 
> * In recovered timeseries the date is formatted as: X/X/2020
> * In deaths and confirmed timeseries it is formatted as: X/X/20

I quote, please fix

**Comment by navmedvideos** [comment] 2020-03-26 10:30
Coronavirus Live Stream - Real-time counter, Maps, and worldwide stats.

https://www.youtube.com/watch?v=qTbR2UKTQQc

**Comment by downFast** [comment] 2020-03-26 10:35
> Coronavirus Live Stream - Real-time counter, Maps, and worldwide stats.
> 
> https://www.youtube.com/watch?v=qTbR2UKTQQc

what does it have to do with this issue?

**Comment by THX1188** [comment] 2020-03-26 10:50
There seems to be another issue with that feed, the three binary digits , special chars, which may come from manual editing, and  that the editor setting was not UTF-8 but some other UTF-encoding which requires the first bytes in a file to describe the format - see screenshot of R-Output, ... The other 2 files are clean.

![R_Province_State_Not_Known](https://user-images.githubusercontent.com/61349287/77638566-a76d0880-6f57-11ea-9d5b-80672579c8ca.PNG)

**Comment by kaeladickens** [comment] 2020-03-26 14:10
Thanks again for providing this data!

Will recoveries begin to be updated again, post-March 24th?

**Comment by cipriancraciun** [comment] 2020-03-27 20:19
It was announced in #1250 that the recovered data will not be available anymore (after March 22nd) due to logistics regarding reporting and scraping.

In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.

**Closed** 2020-03-28 13:17 UTC
